// <auto-generated />
namespace MVC_with_EF__CRUD_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mg4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg4));
        
        string IMigrationMetadata.Id
        {
            get { return "202512171249002_mg4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
